image: rikorose/gcc-cmake:gcc-10

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - cd build
    - ctest . -C Debug
  artifacts:
    reports:
      junit: build/test/report.xml  
